### PR TITLE
properties that had a value of "0" were seen as false (no value) and ignored

### PR DESCRIPTION
**Pull request by BMartinos**
Good day,

I have a found and fixed a small bug within the jsParser that ignored a value if it was 0.
The main missing element was the **total** if a search was done and no resources were found, The total will have a value of zero and will not be included as an element due to the if statement evaluating to false.

Thanks you,

### CODE REVIEW

**Comment by seanmcilvenna** [comment]
Hi @BMartinos, I have reviewed your changes, and will merge them.

Please be aware that I am working on a major re-design of the module which I will be calling v4.0.0. You can see the changes in the [redesign](https://github.com/lantanagroup/fhir.js/tree/redesign) branch. This re-design simplifies serialization in a number of ways, including reducing the external module dependencies and only supporting a single version of FHIR. It also includes (in my opinion) better validation (including validation of value sets baked into the standard).

I will be moving the master branch into a new branch called "pre-r4" for those that want to continue using the old logic, or have serialization support for DSTU1 and STU2.

I plan to pull the trigger on this at the end of the week. In the meantime, I will accept your pull request and merge the changes into the master branch and the soon-to-be pre-r4 branch.

**Comment by BMartinos** [comment]
Great thanks @seanmcilvenna !

Would it be possible to push the latest changes to npm please. 

Also, really looking forward to seeing the redesign that you have been working on!

Regards,
Martin

**Comment by seanmcilvenna** [comment]
I pushed the latest changes to NPM yesterday (version 3.2.0).
I also pushed a beta version of the redesign to NPM (npm install fhir@4.0.0).

**Comment by seanmcilvenna** [comment]
whooops.. maybe I *didn't* push your changes to NPM
will do so today.

**Comment by BMartinos** [comment]
No problem :), Thanks so much for your quick response!

**Comment by seanmcilvenna** [comment]
ok, there we go. published 3.3.0

**Pull request merged**
