### PR TITLE
Dont add meta element if it already exists

### PR DESCRIPTION
**Pull request by lschmierer**
A type fix in my last PR made sure that `ensurePropertyMetaData` is called in the `ParseConformance` constructor.
However, that revealed an issue that additional meta propterties are created for primitives that already have an associated _meta property.
That resulted wrong properties with multiple leading underscores like `__id`, `___id` etc.

This resolves this by filtering for leading underscores in `ensurePropertyMetaData`:
```Js
 const primitiveProperties = properties
                .filter(p => Constants.PrimitiveTypes.indexOf(p._type) >= 0)
                // Constants.PrimitiveTypes contains Element so an additional check for leading underscores is necessary
                .filter(p => !p._name.startsWith('_'));
```
Checking the `property._type != 'Element'` might work as well, but I think the underscore aproach is more robust.

### CODE REVIEW

**Comment by seanmcilvenna** [comment]
Please resolve the conflicts in this branch, and then I will merge...

**Comment by lschmierer** [comment]
I have resolved the merge conflicts

**Comment by seanmcilvenna** [comment]
Merged! Thanks!
Are you needing me to push a patch update to NPM?

**Comment by lschmierer** [comment]
Patch update would be great! Thanks a lot!

**Comment by seanmcilvenna** [comment]
Done! Released on NPM as 4.8.1

**Pull request merged**
